### ISSUE TITLE
Make the "Guess My Number" Game Page Responsive

### ISSUE THREAD

**Issue by Xhz0729** [Xhz0729/techtonica-assignments#25]
The current layout of the "Guess My Number" game is not optimized for different screen sizes. The goal is to ensure that the page is fully responsive and provides a seamless experience across devices such as desktops, tablets, and mobile phones.
Tasks:
Implement media queries to adjust the layout for various screen widths.
Ensure that the input fields, buttons, and other UI elements resize appropriately.
Test the design on both small and large screens to identify any layout issues.

**Comment by nianokia** [comment]
Hi Xiahui!
I'd like to try taking on this issue. Would you mind assigning it to me?

**Comment by Xhz0729** [comment]
Hi Nia,
I've assigned the issue to you!
Thank you for your help!
Xiahui

**Comment by Xhz0729** [comment]
Responsive design being added to the game project.
